level_map=[
        "1                                                                    ",
        "                                                                     ",
        "  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  ", 
        "  X                                               x               X  ",   
        "  X                                               xxxxxxx    E    X  ",
        "  X    ÇXXXXXXç                                         x         X  ",
        "  X    ÇB     ç ÇCCCCCCç                      aaaaaaaa  x         X  ",
        "  X    Ç      ç Ç      ç   FFFFFF            aWWWWWWWa  xxxxxxxxxxX  ",
        "  X    Ç  P   ç Ç S    ç   FFFFFF            aWWWWWWWa            X  ",
        "  X    Ç      ç Ç   S  ç   FFFFFF           aWWWWWWWWa            X  ",
        "  X    CCC  CCC Ç      ç   FFFFFF           aaWWWaaaaa            X  ", 
        "  X             Çccxxccç                      aaa                 X  ",
        "  X                                                               X  ",
        "  X    N                                                          X  ",
        "  X                                                               X  ",
        "  X                                                               X  ",
        "  X                     L                                         X  ",
        "  X                                                               X  ",
        "  X       T                                          E            X  ",
        "  X                                                               X  ",
        "  X                                                               X  ",
        "  X                         E                                     X  ", 
        "  X                                                               X  ", 
        "  X                                                               X  ", 
        "  X          XX                                                   X  ",
        "  X        XXXXXX                                           L     X  ",
        "  X        XXXXXX                                                 X  ",
        "  X        XXXXXX                                                 X  ",
        "  X        XXXXXX                                                 X  ",
        "  X        XXXXXXCCCCç                    L                       X  ",
        "  X        CCCCCC    ç                                            X  ",
        "  X            Ç   L ç                                            X  ",
        "  X         n  Ç L   ç                                            X  ",
        "  X            Ç     ç                                            X  ",
        "  X            ÇccXccç                                            X  ",
        "  X                                                               X  ",
        "  X                                                               X  ",
        "  X                                                               X  ",
        "  X                                                               X  ",
        "  X                                                               X  ",
        "  X                                                               X  ",
        "  XxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxX  ",
        "  X                                           E                   X  ",
        "  X                                                               X  ",
        "  X                                                               X  ",
        "  X                                                               X  ",
        "  X                                 E                             X  ",
        "  X                                                               X  ",
        "  X                   E                                           X  ",
        "  X                                                               X  ",
        "  X                                                               X  ",
        "  X                                                               X  ",
        "  X                              E                                X  ",
        "  X                                                      A        X  ",
        "  X                                                               X  ",
        "  X             Ğ                                                 X@@@@@@",
        "  X                                                               X     @",
        "  X                                           E                   G     @",
        "  X                                                               G     @",
        "  XxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxG     @",
        "  X                                                               X     @",
        "  XWWWWW                    Ğ                                     X@@@@@@",
        "  XWWWWWWWWWW                                     Ğ               X  ",
        "  XWWWWWWWWWW                                                     X  ",
        "  XWWWWWWWWWWWWWWWWWWWWWWW   WWWWWWWWWW                           X  ",
        "  XWWWWWWWWWWWWWWWWWWWWWWW   WWWWWWWWWW                           X  ",
        "  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  ",
]
tile_size=32
en=900
boy=640